const investissementTypeActuions = {
  FETCH_INVESTISSEMENT_BY_ID_SUCCESS: "FETCH_INVESTISSEMENT_BY_ID_SUCCESS",
  VALIDATION_INVESTISSEMENT_SUCCESS: "VALIDATION_INVESTISSEMENT_SUCCESS",
  REJECT_INVESTISSEMENT_SUCCESS: "REJECT_INVESTISSEMENT_SUCCESS",
  FETCH_INVESTISSEMENT_START: "FETCH_INVESTISSEMENT_START",
  FETCH_INVESTISSEMENT_BY_STRUCTURE_SUCCESS:
    "FETCH_INVESTISSEMENT_BY_STRUCTURE_SUCCESS",
  FETCH_INVESTISSEMENT_SUCCESS: "FETCH_INVESTISSEMENT_SUCCESS",
  FETCH_INVESTISSEMENT_FAILLURE: "FETCH_INVESTISSEMENT_FAILLURE",
  STORE_INVESTISSEMENT_SUCCESS: "STORE_INVESTISSEMENT_SUCCESS",
  UPDATE_INVESTISSEMENT_SUCCESS: "UPDATE_INVESTISSEMENT_SUCCESS",
  REMOVE_INVESTISSEMENT_SUCCESS: "REMOVE_INVESTISSEMENT_SUCCESS",
  RESET_EDITED_INVESTISSEMENT: "RESET_EDITED_INVESTISSEMENT",
};
export default investissementTypeActuions;
