const structureActionTypes ={
    GET_STRUCTURE_DATA : 'GET_STRUCTURE_DATA',
    GET_TYPE_ACTEUR: 'GET_TYPE_ACTEUR',
    GET_CURRENT_STRUCTURE: 'GET_CURRENT_STRUCTURE',
    FETCH_STRUCTURE_BY_ID:'FETCH_STRUCTURE_BY_ID',
    FETCH_STRUCTURE_START: 'FETCH_STRUCTURE_START',
    FETCH_STRUCTURE_SUCCESS: 'FETCH_STRUCTURE_SUCCESS',
    FETCH_STRUCTURE_FAILLURE: 'FETCH_STRUCTURE_FAILLURE',
    STORE_STRUCTURE_SUCCESS:'STORE_STRUCTURE_SUCCESS',
    UPDATE_STRUCTURE_SUCCESS:'UPDATE_STRUCTURE_SUCCESS',
    REMOVE_STRUCTURE_SUCCESS:'REMOVE_STRUCTURE_SUCCESS',
    RESET_EDITED_STRUCTURE:'RESET_EDITED_STRUCTURE'
}

export default structureActionTypes;