const structureActionTypes ={
    GET_STRUCTURE_DATA : 'GET_STRUCTURE_DATA',
    GET_TYPE_ACTEUR: 'GET_TYPE_ACTEUR',
    GET_CURRENT_STRUCTURE: 'GET_CURRENT_STRUCTURE',

    FETCH_STRUCTURE_START: 'FETCH_STRUCTURE_START',
    FETCH_STRUCTURE_SUCCESS: 'FETCH_STRUCTURE_SUCCESS',
    FETCH_STRUCTURE_FAILLURE: 'FETCH_STRUCTURE_FAILLURE',
}

export default structureActionTypes;