const districteTypeActions = {
    FETCH_DISTRICTE_BY_ID: 'FETCH_DISTRICTE_BY_ID',
    FETCH_DISTRICTE_START: 'FETCH_DISTRICTE_START',
    FETCH_DISTRICTE_SUCCESS: 'FETCH_DISTRICTE_SUCCESS',
    FETCH_DISTRICTE_FAILLURE: 'FETCH_DISTRICTE_FAILLURE',
    STORE_DISTRICTE_SUCCESS: 'STORE_DISTRICTE_SUCCESS',
    UPDATE_DISTRICTE_SUCCESS: 'UPDATE_DISTRICTE_SUCCESS',
    REMOVE_DISTRICTE_SUCCESS:'REMOVE_USER_SUCCESS',
    RESET_EDITED_DISTRICTE:'RESET_EDITED_DISTRICTE',

}
export default districteTypeActions;