const roleTypeActuions = {
    FETCH_ROLE_BY_ID: 'FETCH_ROLE_BY_ID',
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILLURE: 'FETCH_ROLE_FAILLURE',
    STORE_ROLE_SUCCESS: 'STORE_ROLE_SUCCESS',
    UPDATE_ROLE_SUCCESS: 'UPDATE_ROLE_SUCCESS',
    REMOVE_ROLE_SUCCESS:'REMOVE_USER_SUCCESS',
    FETCH_PERMISSION_SUCCESS:'FETCH_PERMISSION_SUCCESS',
    RESET_EDITED_ROLE:'RESET_EDITED_ROLE'

}
export default roleTypeActuions;