const acteurTypeActuions = {
    FETCH_ACTEUR_BY_ID: 'FETCH_ACTEUR_BY_ID',
    FETCH_ACTEUR_BY_FINACEMENT: 'FETCH_ACTEUR_BY_FINACEMENT',
    FETCH_ACTEUR_START: 'FETCH_ACTEUR_START',
    FETCH_ACTEUR_SUCCESS: 'FETCH_ACTEUR_SUCCESS',
    FETCH_ACTEUR_FAILLURE: 'FETCH_ACTEUR_FAILLURE',
    STORE_ACTEUR_SUCCESS: 'STORE_ACTEUR_SUCCESS',
    UPDATE_ACTEUR_SUCCESS: 'UPDATE_ACTEUR_SUCCESS',
    REMOVE_ACTEUR_SUCCESS:'REMOVE_ACTEUR_SUCCESS',
    RESET_EDITED_ACTEUR:'RESET_EDITED_ACTEUR'

}
export default acteurTypeActuions;