const userTypeActuions = {
    FETCH_USER_BY_ID: 'FETCH_USER_BY_ID',
    FETCH_USER_BY_STRUCTURE: 'FETCH_USER_BY_STRUCTURE',
    RESET_EDITED_USER: 'RESET_EDITED_USER',
    ACTIVE_STATUS_USER: 'ACTIVE_STATUS_USER',
    
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILLURE: 'FETCH_USER_FAILLURE',
    FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
    STORE_USER_SUCCESS: 'STORE_USER_SUCCESS',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_CURRENT_USER_SUCCESS: 'UPDATE_CURRENT_USER_SUCCESS',
    REMOVE_USER_SUCCESS:'REMOVE_USER_SUCCESS'

}
export default userTypeActuions;