const sourceFinancementActionTypes ={
    ADD_ACCTEUR_FIELD : 'ADD_ACCTEUR_FIELD',
    REMOVE_ACCTEUR_FIELD : 'REMOVE_ACCTEUR_FIELD',
    FETCH_SOURCE_FINANCEMENT_START: 'FETCH_SOURCE_FINANCEMENT_START',
    FETCH_SOURCE_FINANCEMENT_SUCCESS: 'FETCH_SOURCE_FINANCEMENT_SUCCESS',
    FETCH_SOURCE_FINANCEMENT_FAILLURE: 'FETCH_SOURCE_FINANCEMENT_FAILLURE',
    FETCH_SOURCE_FINANCEMENT_BY_ID:'FETCH_SOURCE_FINANCEMENT_BY_ID',
    FETCH_SOURCE_FINANCEMENT_BY_ID: 'FETCH_SOURCE_FINANCEMENT_BY_ID',
    STORE_SOURCE_FINANCEMENT_SUCCESS: 'STORE_SOURCE_FINANCEMENT_SUCCESS',
    UPDATE_SOURCE_FINANCEMENT_SUCCESS: 'UPDATE_SOURCE_FINANCEMENT_SUCCESS',
    REMOVE_SOURCE_FINANCEMENT_SUCCESS:'REMOVE_SOURCE_FINANCEMENT_SUCCESS',
    RESET_EDITED_SOURCE_FINANCEMENT:'RESET_EDITED_SOURCE_FINANCEMENT'
}

export default sourceFinancementActionTypes;