const sourceFinancementActionTypes ={
    GET_SOURCE_FINANCEMENT_DATA : 'GET_SOURCE_FINANCEMENT_DATA',
    ADD_ACCTEUR_FIELD : 'ADD_ACCTEUR_FIELD',
    REMOVE_ACCTEUR_FIELD : 'REMOVE_ACCTEUR_FIELD',


    FETCH_SOURCE_FINANCEMENT_START: 'FETCH_SOURCE_FINANCEMENT_START',
    FETCH_SOURCE_FINANCEMENT_SUCCESS: 'FETCH_SOURCE_FINANCEMENT_SUCCESS',
    FETCH_SOURCE_FINANCEMENT_FAILLURE: 'FETCH_SOURCE_FINANCEMENT_FAILLURE',
}

export default sourceFinancementActionTypes;