const collectiviteTypeActions = {
    FETCH_COLLECTIVITE_BY_ID: 'FETCH_COLLECTIVITE_BY_ID',
    FETCH_COLLECTIVITE_START: 'FETCH_COLLECTIVITE_START',
    FETCH_COLLECTIVITE_SUCCESS: 'FETCH_COLLECTIVITE_SUCCESS',
    FETCH_COLLECTIVITE_FAILLURE: 'FETCH_COLLECTIVITE_FAILLURE',
    STORE_COLLECTIVITE_SUCCESS: 'STORE_COLLECTIVITE_SUCCESS',
    UPDATE_COLLECTIVITE_SUCCESS: 'UPDATE_COLLECTIVITE_SUCCESS',
    REMOVE_COLLECTIVITE_SUCCESS:'REMOVE_COLLECTIVITE_SUCCESS',
    RESET_EDITED_COLLECTIVITE:'RESET_EDITED_COLLECTIVITE',
    FETCH_COLLECTIVITE_BY_PARENT_CODE:'FETCH_COLLECTIVITE_BY_PARENT_CODE',
    FETCH_REGION_SUCCESS:'FETCH_REGION_SUCCESS',
    RESET_COLLECTIVITE_BY_CODE_PARENT:'RESET_COLLECTIVITE_BY_CODE_PARENT'


}
export default collectiviteTypeActions;